### ISSUE TITLE
7426 legespesialitet inn i practitioner qualification

### ISSUE THREAD

**Issue by thomiz** [HL7Norway/basisprofiler-r3#28]
Practitioner kom det innspill på at vi  7426 (legespesialiteter) kunne brukes i Practitioner i stedet for PractitionerRole. Representerer en egenskap ved helsepersonell mer enn rollen.

**Comment by ellgre** [comment]
Er det ikke egentlig behov for denne informasjonen begge steder? En practitioner kan ha flere legespesialiteter og man har behov for å kunne si hvilken av spesialitetene rollen gjelder for. Tilsvarende har man for practitioners med godkjenning i flere yrkesgrupper (f.eks lege og tannlege) behov for å angi hvilken av yrkesgruppene rollen gjelder for.
Eller har man tenkt til å løse dette på en anne måte?

**Comment by rockphotog** [comment]
Godt spørsmål. Vi trenger spesialitet begge steder. 7426 er tilknyttet HPR. Jeg tror vi må ta en runde med spesialist hva de bruker internt - er det HPR er det jo greit. Hovedoppgaven blir uansett å se om vi kan samkjøre de 3-4 forskjellige kodeverkene for spesialitet. Tror det kan være en god case for å bruke SNOMED CT som referansekodeverk for administrative koder.

**Comment by ellgre** [comment]
Med tanke på at spesialister finnes både i HPR og i profesjonsforeningene (for eksempel psykolog og fysioterapi) kan det være en god idé å se på hva SNOMED har å tilby for å få et felles kodeverk.

**Comment by rockphotog** [comment]
SNOMED CT skal i forbindelse med International Patient Summary "frigi" 8000 koder som skal støtte implementering av IPS i FHIR (og CDA), forhåpentligvis før sommeren. Jeg håper at det vil være et valueset for spesialitet som vi da kan bruke som utgangspunkt for å mappe inn 7426 og de andre. PractitionerRole er for tiden ikke med i IPS
https://build.fhir.org/ig/HL7/fhir-ips/index.html

...men selvfølgelig Practitioner (med begrepet qualification i stedet for speciality). 

Jeg skal uansett sørge for at Avdeling helsefaglige kodeverk og terminologi hos Dir e-helse får problemstillingen på pulten sin.

**Comment by oaassv** [comment]
Fagområde er et komplekst område som totalt sett over et titalls  kodeverk med litt ulike formål knyttet til kliniske spesialiteter og er nært knyttet til klassifisering av organisasjonsenheter. Her er det over et titalls delvis overlappende kodeverk i tillegg til Helsetjenestekatalogen i bruk i dag. På lang sikt bør vi få til en helhetlig løsning hvor disse områdene er dekket på en helhetlig måte i forhold til totalt kodingsbehov i arbeidsflyt. 



--------------------------------------------
Den fre, 4/5/19 skrev Espen Stranger Seland <notifications@github.com>:

 Emne: Re: [HL7Norway/basisprofiler-r3] 7426 legespesialitet inn i practitioner qualification (#28)
 Til: "HL7Norway/basisprofiler-r3" <basisprofiler-r3@noreply.github.com>
 Kopi: "Subscribed" <subscribed@noreply.github.com>
 Dato: Fredag, april 5, 2019, 10:30 AM
 
 SNOMED CT skal i
 forbindelse med International Patient Summary
 "frigi" 8000 koder som skal støtte implementering
 av IPS i FHIR (og CDA), forhåpentligvis før sommeren. Jeg
 håper at det vil være et valueset for spesialitet som vi
 da kan bruke som utgangspunkt for å mappe inn 7426 og de
 andre. PractitionerRole er for tiden ikke med i IPS
 
 https://build.fhir.org/ig/HL7/fhir-ips/index.html
 ...men selvfølgelig Practitioner (med begrepet
 qualification i stedet for speciality).
 Jeg skal uansett sørge for at Avdeling helsefaglige
 kodeverk og terminologi hos Dir e-helse får
 problemstillingen på pulten sin.
 
 —
 You are
 receiving this because you are subscribed to this thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by thomiz** [comment]
Forslaget går vel ut på å uttrykke spesialiteten knyttet til rolle ved hjelp av andre kodeverk enn 7426 som er spesialiteten knyttet til kvalifikasjonen helsepersonen har godkjent og registrert i HPR registeret. Idag er det vel ihvertfall slik at disse egentlig ikke er nøyaktig sammenfallende og det kodes forskjellig i rollen og kvalifikasjonen, noe som også er logisk siden kvalifikasjon er noe annet en funksjon.

**Comment by oaassv** [comment]
HP har etterspurt dette fra PK, og Arkitekturstyring nevner dette konkret i sin tilbakemelding til PKT. I dag er det en rekke kodeverk som helt eller delvis overlapper med hensyn på å beskrive fagområdet/ organisasjon etc. Kodeverk inkluderer 8451, 7426, 8668, 8660, 8666, Helsetjenestekatalogen, 8452, 8451, 8663, 9151,  8453, 8664, 8656, 8654. Det hadde vært nyttig om PKT kunne se helhetlig på disse kodeverkene, og hvordan SNOMED CT eventuelt kan bidra til harmonisering. Det er imildertid helt klart et mer langsiktig løp.

**Comment by ellgre** [comment]
I HL7-spekken har de anbefalt følgende kodeverk for Specialty på PractitionerRole https://www.hl7.org/fhir/valueset-c80-practice-codes.html. Dette kommer fra Snomed. Er dette noe som er aktuelt å bruke for Norge?

**Comment by oaassv** [comment]
For det langsiktige løpet er det en mulig vei å gå. På kort sikt må vi forholde oss til de kodeverkene vi har, og så må Helseplattformen/ PKT utrede om det er mulig å få til mer helhetlige løsninger basert på SNOMED CT. For det vil det også være viktig å se på hvordan en migrering eventuelt kan skje for kodeverk som er installert i mange systemer i produksjon, med overlappende innhold som til dels er utviklet for litt ulike formål.

**Comment by rockphotog** [comment]
Lukkes, erstattes av https://github.com/HL7Norway/basisprofiler-r4/issues/7
